<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clase 31 - MManejo de errores con callbacks</title>
</head>
<body>
    <script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
  crossorigin="anonymous"></script>
    <section>
        <h1>Manejando el Orden y el Asincronismo en JavaScript</h1>
        <div class="Description-agenda">
            <p>Para solucionar el problema de quedarnos sin conexión, u otro error similar, en medio de una sucesión de callbacks utilizamos el método fail().</p>
        </div>
    </section>
    <script src="clase31.js"></script>
</body>
</html>